### ISSUE TITLE
Migrate Gerty to Vivi

### ISSUE THREAD

**Issue by michael-beaver** [siggame/vivi#10]
Gerty is the bot that we use to update status.megaminerai.com and we need to be able to use her on discord. How it was done back when we used Slack was it had it's own channel and only people authorized to update the site could use the channel

Here is the old repo: https://github.com/siggame/gerty

**Comment by Uhuh** [comment]
Could you possibly elaborate exactly what Gerty does and the specifics so I can figure out what needs to be done.
For example look at this issue I made, https://github.com/siggame/vivi/issues/9
Could you please make bullet points of you want to be achieved. Done by.. 
` - [ ] This is a bullet point that can be checked` Will look like..
 - [ ] This is a bullet point that can be checked

**Comment by user404d** [comment]
@michael-beaver @Uhuh I am bumping this up to high priority, please try to help each other out on this

**Comment by michael-beaver** [comment]
So the gerty's main function is to update [status.megaminerai.com](http://status.megaminerai.com) , the repo for which can be found here: https://github.com/siggame/status

The main command on gerty was update
it would be used like this: 
```
gerty update <component> to <status>; <title>: <message> - Post a new status update
```
Where the component was from Arena, Food, Gameserver, Git, Visualizer, Gameserver
and the status was from OK, Down, and Warning
the title would be the title on the updated page and the message would be the explanation text under it

Now for our purposes, we would no longer need Git, maybe replace it with the Website/Webserver? Not sure why we didn't have that before

There were several other commands that gerty could accomplish, but that is the main one that we need.

- [ ] gerty update <component> to <status>; <title>: <message> - Post a new status update
