### ISSUE TITLE
Vivi's @{role} is not notifying users, find out why.

### ISSUE THREAD

**Issue by Uhuh** [siggame/vivi#12]
So when a reminder is sent out, Vivi will do "`@PR` blah blah" Or "`@Arena`" Etc, we'll notice the `@PR` didn't work but last week `@everyone` did. Let's figure out why.

**Comment by arena** [comment]
...but your issue is notifying github users. Please use code commenting with referencing variables. 🍻

**Comment by Uhuh** [comment]
Thanks, I wasn't aware of that lmao.
