### ISSUE TITLE
Allow Vivi to cancel a meeting for the week.

### ISSUE THREAD

**Issue by Uhuh** [siggame/vivi#14]
Make a command... probably `!cancel Arena` and it should push the Arena teams meeting up a week.

- Only users with the `Lead` role should be able to use this, so if a normie uses it it should reply with.
  `You do not have the correct role to cancel this meeting.`
- Make sure it doesn't bug out in direct messages (do a check)
- Only push a meeting to the next week. (One week)

- Should Vivi also notify users that the meeting has been canceled?

**Comment by user404d** [comment]
I think all of these seem reasonable. The last one also sounds good.
