### ISSUE TITLE
:bikini: :beaver: 

### ISSUE THREAD

**Issue by MatthewQualls** [siggame/vivi#17]
![hblv0 2](https://user-images.githubusercontent.com/17015528/31642605-688ddf96-b2b1-11e7-8cde-f296c042ac02.png)

**Comment by Uhuh** [comment]
This issue doesn't explain anything. Closed.

**Comment by MatthewQualls** [comment]
I believe it is self descriptive

**Comment by Uhuh** [comment]
It seriously doesn't, either give it a description or leave it closed.

**Comment by MatthewQualls** [comment]
if :bikini: :beaver: then post image

**Comment by Uhuh** [comment]
Pushed to master....
